 ### Music Genre Classification

 This Jupyter Notebook demonstrates how to build a music genre classifier using a pre-extracted dataset.

 We will use a Random Forest model from scikit-learn to train and evaluate the model.

 The data used is the GTZAN dataset, with features pre-extracted into `features_30_sec.csv`.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np


KeyboardInterrupt: 

 ### Data Loading and Preprocessing

 We'll load the data from the CSV file, separate the features from the labels, and prepare it for our model.

In [3]:
# Path to the CSV file with pre-extracted features
data_file_path = "C:\\Users\\SCAIPL\\Desktop\\Music Classifier\\Data\\features_30_sec.csv"

# Load the features and labels from the CSV file
print("Loading data...")
df = pd.read_csv(data_file_path)

# Drop the filename column as it's not a useful feature for training
df = df.drop(['filename'], axis=1)

# Separate features (X) and labels (y)
X = df.drop('label', axis=1).values
y = df['label'].values


Loading data...


 ### Label Encoding and Feature Scaling

 To ensure our model works correctly, we need to convert the text labels into numbers and normalize the numerical features.

In [4]:
# Encode genre labels into numerical values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Normalize the features to ensure all features are on a similar scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Data preprocessing complete!")


Data preprocessing complete!


 ### Splitting the Dataset

 We'll split the data into training and testing sets to evaluate the model's performance on unseen data.

In [5]:
# Split the data into training (80%) and testing (20%) sets
# stratify=y_encoded ensures that the proportion of genres is the same in both sets
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)


 ### Model Training

 Now we initialize and train the **Random Forest Classifier**.

In [6]:
print("Training the classifier...")
# Initialize the RandomForestClassifier with 100 trees
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model to the training data
model.fit(X_train, y_train)
print("Training complete!")


Training the classifier...
Training complete!


 ### Model Evaluation

 Finally, we'll evaluate the model using its accuracy and a confusion matrix to understand its performance in more detail.

In [7]:
print("Evaluating model performance...")
# Make predictions on the unseen test set
y_pred = model.predict(X_test)

# Calculate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy:.2f}")

# Generate and print the confusion matrix for a detailed breakdown
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

# Print the genre names to help interpret the confusion matrix
genre_names = label_encoder.inverse_transform(range(len(label_encoder.classes_)))
print("\nGenre Labels (for Confusion Matrix):")
for i, genre in enumerate(genre_names):
    print(f"{i}: {genre}")

Evaluating model performance...

Model Accuracy: 0.78

Confusion Matrix:
[[15  0  2  0  0  0  0  0  2  1]
 [ 0 19  0  0  0  1  0  0  0  0]
 [ 0  0 15  0  0  2  0  0  1  2]
 [ 0  1  1 12  5  0  1  0  0  0]
 [ 1  0  0  2 15  0  1  0  0  1]
 [ 1  2  0  0  0 17  0  0  0  0]
 [ 0  0  0  2  0  0 17  0  1  0]
 [ 0  0  0  0  1  0  0 18  1  0]
 [ 0  0  0  0  1  0  0  3 16  0]
 [ 2  0  3  1  1  2  0  0  0 11]]

Genre Labels (for Confusion Matrix):
0: blues
1: classical
2: country
3: disco
4: hiphop
5: jazz
6: metal
7: pop
8: reggae
9: rock


In [8]:
from sklearn.metrics import classification_report

# Assuming you still have y_test and y_pred
print(classification_report(y_test, y_pred, target_names=genre_names))

              precision    recall  f1-score   support

       blues       0.79      0.75      0.77        20
   classical       0.86      0.95      0.90        20
     country       0.71      0.75      0.73        20
       disco       0.71      0.60      0.65        20
      hiphop       0.65      0.75      0.70        20
        jazz       0.77      0.85      0.81        20
       metal       0.89      0.85      0.87        20
         pop       0.86      0.90      0.88        20
      reggae       0.76      0.80      0.78        20
        rock       0.73      0.55      0.63        20

    accuracy                           0.78       200
   macro avg       0.77      0.78      0.77       200
weighted avg       0.77      0.78      0.77       200



In [9]:
import joblib

# After training is complete
joblib.dump(model, 'genre_classifier_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(label_encoder, 'label_encoder.pkl')

print("Saved model, scaler, and encoder to disk!")

Saved model, scaler, and encoder to disk!


In [10]:
import pandas as pd
df = pd.read_csv("C:\\Users\\SCAIPL\\Desktop\\Music Classifier\\Data\\features_30_sec.csv")
print(df.columns.tolist())

['filename', 'length', 'chroma_stft_mean', 'chroma_stft_var', 'rms_mean', 'rms_var', 'spectral_centroid_mean', 'spectral_centroid_var', 'spectral_bandwidth_mean', 'spectral_bandwidth_var', 'rolloff_mean', 'rolloff_var', 'zero_crossing_rate_mean', 'zero_crossing_rate_var', 'harmony_mean', 'harmony_var', 'perceptr_mean', 'perceptr_var', 'tempo', 'mfcc1_mean', 'mfcc1_var', 'mfcc2_mean', 'mfcc2_var', 'mfcc3_mean', 'mfcc3_var', 'mfcc4_mean', 'mfcc4_var', 'mfcc5_mean', 'mfcc5_var', 'mfcc6_mean', 'mfcc6_var', 'mfcc7_mean', 'mfcc7_var', 'mfcc8_mean', 'mfcc8_var', 'mfcc9_mean', 'mfcc9_var', 'mfcc10_mean', 'mfcc10_var', 'mfcc11_mean', 'mfcc11_var', 'mfcc12_mean', 'mfcc12_var', 'mfcc13_mean', 'mfcc13_var', 'mfcc14_mean', 'mfcc14_var', 'mfcc15_mean', 'mfcc15_var', 'mfcc16_mean', 'mfcc16_var', 'mfcc17_mean', 'mfcc17_var', 'mfcc18_mean', 'mfcc18_var', 'mfcc19_mean', 'mfcc19_var', 'mfcc20_mean', 'mfcc20_var', 'label']
